apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chainflip-lp-exporter.fullname" . }}
  labels:
    {{- include "chainflip-lp-exporter.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- tpl .Values.config . | nindent 4 }}