apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainflip-lp-exporter.fullname" . }}
  labels:
    {{- include "chainflip-lp-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chainflip-lp-exporter.selectorLabels" . | nindent 4 }}
