replicaCount: 1

image:
  repository: jitstrategies/jitcord
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  # discord_token: "" # REQUIRED
  target: "" # REQUIRED

# Secret that contains env vars
secretEnv: {}
  # - name: JITCORD_DISCORD_TOKEN
  #   secretKeyRefName: discord-bot-token
  #   secretKeyRefKey: JITCORD_DISCORD_TOKEN

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Add here extra manifests like ad-hoc secrets.
extraObjects: {}