apiVersion: v1
kind: Service
metadata:
  name: {{ include "blutgang.fullname" . }}
  labels:
    {{- include "blutgang.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: httpPort
      protocol: TCP
      name: http
    - port: {{ .Values.adminRPCPort }}
      targetPort: adminRPCPort
      protocol: TCP
      name: admin
  selector:
    {{- include "blutgang.selectorLabels" . | nindent 4 }}
